### ISSUE TITLE
Cant install wheel

### ISSUE THREAD

**Issue by eli-collins** [bwesterb/argon2pure#1]
As of release 1.1, I think there's a typo in setup.py -- the line that reads `py_modules="argon2pure"` should read `py_modules=['argon2pure']`.  Otherwise project isn't installable except via `setup.py develop`.

**Comment by bwesterb** [comment]
Should be fixed in 1.1.1.  Can you confirm? Thank you very much for reporting!  By the way, this reminds me I should add support for argon2 version 1.3.  I will fix that soon.

**Comment by bwesterb** [comment]
I added support for Argon2 v1.3 in 1.2.
